/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ComparerRouteImport } from './routes/comparer'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as SaisieRouteImport } from './routes/saisie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparerRoute = ComparerRouteImport.update({
  id: '/comparer',
  path: '/comparer',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieRoute = SaisieRouteImport.update({
  id: '/saisie',
  path: '/saisie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/comparer': typeof ComparerRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/comparer': typeof ComparerRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/comparer': typeof ComparerRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/resultats': typeof ResultatsRoute
  '/saisie': typeof SaisieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/comparer'
    | '/politique-confidentialite'
    | '/resultats'
    | '/saisie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/comparer'
    | '/politique-confidentialite'
    | '/resultats'
    | '/saisie'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/comparer'
    | '/politique-confidentialite'
    | '/resultats'
    | '/saisie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  ComparerRoute: typeof ComparerRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ResultatsRoute: typeof ResultatsRoute
  SaisieRoute: typeof SaisieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparer': {
      id: '/comparer'
      path: '/comparer'
      fullPath: '/comparer'
      preLoaderRoute: typeof ComparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie': {
      id: '/saisie'
      path: '/saisie'
      fullPath: '/saisie'
      preLoaderRoute: typeof SaisieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  ComparerRoute: ComparerRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ResultatsRoute: ResultatsRoute,
  SaisieRoute: SaisieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
